name: '📦  Install'
description: 'Localized Install'

inputs:
  OPTIONAL_INSTALL_COMMAND:
    description: 'Optional Install String for Run Script'
    default: '--prefer-offline'
    required: false

runs:
  using: 'composite'
  steps:
    - name: '📦️  Dependencies'
      id: dependencies
      shell: bash
      run: |
        pnpm install ${{ inputs.OPTIONAL_INSTALL_COMMAND }}