name: 'ЁЯЪия╕П Lint, TypeCheck, and Test'
description: 'Localized Lint'

inputs:
  TURBO_TEAM:
    description: 'ID for Turbo'
    required: false
  TURBO_TOKEN:
    description: 'ID for Turbo'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'ЁЯЪия╕П  Lint'
      id: lint
      shell: bash
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      run: |
        pnpm run lint && pnpm run type:check && pnpm vitest --run