name: '💽️  Init'
description: 'Localized Init'

inputs:
  PNPM_VERSION:
    description: 'Version of PNPM to use'
    default: '8'
    required: false
  NODE_VERSION:
    description: 'Version of Node to use'
    default: '18'
    required: false

runs:
  using: 'composite'
  steps:
    - name: '🔧  pnpm'
      id: pnpm-setup
      uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.PNPM_VERSION }}

    - name: '💽️  Node'
      id: node-setup
      uses: actions/setup-node@v3
      with:
        # architecture: 'x64'
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version: ${{ inputs.NODE_VERSION }}